-- Users are created lazily from the Auth0 "sub" claim on their first authenticated request.
create table app_users (
    id            bigint generated by default as identity primary key,
    auth0_subject varchar(255) not null unique,
    email         varchar(320),
    display_name  varchar(120) not null,
    avatar_url    varchar(1024),
    created_at    timestamp with time zone not null
);

create table campaigns (
    id          bigint generated by default as identity primary key,
    name        varchar(120) not null,
    description text,
    invite_code varchar(32) not null unique,
    created_at  timestamp with time zone not null
);

-- Roles are scoped to a campaign: the same person can own one campaign and play in another.
create table campaign_members (
    id          bigint generated by default as identity primary key,
    campaign_id bigint not null references campaigns (id) on delete cascade,
    user_id     bigint not null references app_users (id) on delete cascade,
    role        varchar(16) not null,
    joined_at   timestamp with time zone not null,
    constraint uq_campaign_member unique (campaign_id, user_id),
    constraint ck_campaign_member_role check (role in ('OWNER', 'MASTER', 'PLAYER'))
);

create table game_maps (
    id           bigint generated by default as identity primary key,
    campaign_id  bigint not null references campaigns (id) on delete cascade,
    name         varchar(120) not null,
    description  text,
    storage_key  varchar(255) not null,
    content_type varchar(100) not null,
    width        integer not null,
    height       integer not null,
    created_at   timestamp with time zone not null,
    updated_at   timestamp with time zone not null
);

-- campaign_id is null for the built-in catalogue shared by every campaign.
create table marker_types (
    id          bigint generated by default as identity primary key,
    campaign_id bigint references campaigns (id) on delete cascade,
    name        varchar(60) not null,
    shape       varchar(16) not null,
    color       varchar(7)  not null,
    icon        varchar(16),
    sort_order  integer     not null default 0,
    constraint ck_marker_type_shape check (shape in ('CIRCLE', 'SQUARE', 'DIAMOND', 'TRIANGLE', 'HEXAGON', 'STAR', 'PIN', 'SHIELD'))
);

create table markers (
    id             bigint generated by default as identity primary key,
    map_id         bigint not null references game_maps (id) on delete cascade,
    marker_type_id bigint not null references marker_types (id),
    title          varchar(120) not null,
    description    text,
    gm_notes       text,
    pos_x          double precision not null,
    pos_y          double precision not null,
    visibility     varchar(16) not null,
    created_at     timestamp with time zone not null,
    updated_at     timestamp with time zone not null,
    constraint ck_marker_visibility check (visibility in ('VISIBLE', 'HIDDEN'))
);

create index ix_markers_map on markers (map_id);

-- Personal notes a member pins to a marker. Only the author can ever read them.
create table marker_notes (
    id         bigint generated by default as identity primary key,
    marker_id  bigint not null references markers (id) on delete cascade,
    author_id  bigint not null references app_users (id) on delete cascade,
    content    text   not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create index ix_marker_notes_author on marker_notes (author_id, marker_id);

create table characters (
    id          bigint generated by default as identity primary key,
    campaign_id bigint not null references campaigns (id) on delete cascade,
    owner_id    bigint not null references app_users (id) on delete cascade,
    name        varchar(120) not null,
    sheet_json  text   not null,
    created_at  timestamp with time zone not null,
    updated_at  timestamp with time zone not null
);

create index ix_characters_campaign on characters (campaign_id, owner_id);

create table character_notes (
    id           bigint generated by default as identity primary key,
    character_id bigint not null references characters (id) on delete cascade,
    title        varchar(160) not null,
    content      text,
    created_at   timestamp with time zone not null,
    updated_at   timestamp with time zone not null
);

create table session_logs (
    id             bigint generated by default as identity primary key,
    campaign_id    bigint not null references campaigns (id) on delete cascade,
    author_id      bigint references app_users (id) on delete set null,
    session_number integer,
    title          varchar(200) not null,
    played_on      date,
    summary        text,
    content        text,
    published      boolean not null default false,
    created_at     timestamp with time zone not null,
    updated_at     timestamp with time zone not null
);

create index ix_session_logs_campaign on session_logs (campaign_id);
